// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// booksDao is the data access object for the table books.
// You can define custom methods on it to extend its functionality as needed.
type booksDao struct {
	*internal.BooksDao
}

var (
	// Books is a globally accessible object for table books operations.
	Books = booksDao{internal.NewBooksDao()}
)

// Add your custom methods and functionality below.
