// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// borrowRecordsDao is the data access object for the table borrow_records.
// You can define custom methods on it to extend its functionality as needed.
type borrowRecordsDao struct {
	*internal.BorrowRecordsDao
}

var (
	// BorrowRecords is a globally accessible object for table borrow_records operations.
	BorrowRecords = borrowRecordsDao{internal.NewBorrowRecordsDao()}
)

// Add your custom methods and functionality below.
